#!/bin/bash
# Run composer install

echo "composer install"

cd app-root/runtime/repo/php

export HOME_ORIGIN=$HOME
export HOME=$HOME/app-root/runtime/repo/php

/opt/rh/php54/root/usr/bin/php

# /usr/bin/php composer.phar install
/opt/rh/php54/root/usr/bin/php composer.phar install

export HOME=$HOME_ORIGIN
