#!/bin/bash
# Run install script update

echo "install-scripts update"

cd app-root/runtime/repo/php

/usr/bin/php index.php install-scripts update

rm -rf data/cache/config/*
rm -rf data/cache/data/*
rm -rf data/cache/output/*
