<?php
$this->headTitle('List');

/** @var \Application\Form\Form\Transaction $form */
/** @var \Zend\Form\View\Helper\Form $formHelper */
$orderBy    = $this->order_by;
$order      = $this->order;
$formHelper = $this->form();
$form       = $this->form;
$form->setAttributes(array(
    'id'        => 'list',
    'name'      => 'list',
    'action'    => $this->url('list'),
    'style'     => 'width:100%',
    'data-ajax' => 'false'
))->prepare();


$columns = array(
    //'transaction_id' => $this->translate('Id'),
    'item_name'      => $this->translate('Item'),
    'group_name'     => $this->translate('Group'),
    'price'          => $this->translate('Price'),
    //'currency_html'  => $this->translate('Currency'),
    'date'           => $this->translate('Date'),
    //'date_created'   => $this->translate('Created'),
    'id_user'        => $this->translate('User'),
);

$urlOrder = array();
foreach ($columns as $key => $val) {
    if ($orderBy == $key) {
        $urlOrder[$key] = $order == 'ASC' ? 'DESC' : 'ASC';
    } else {
        $urlOrder[$key] = 'ASC';
    }
}

$i = 0;


function getGridVal($i)
{
    $iterator = array('a', 'b', 'c', 'd', 'e');
    echo $iterator[$i];
    $i++;
    if ($i >= 5) {
        $i = 0;
    }
    return $i;
}

$formElements = $form->getElements();
?>

<div class="ui-grid-d" >

    <?php echo $formHelper->openTag($form); ?>
        <?php foreach ($columns AS $key => $label) : ?>
            <?php
            /** @var \Zend\Form\Element $element */
            $element = $formElements[str_replace('_name', '', $key)];
            //$element->setAttribute('required', '');

            $formElementErrors = $this->formElementErrors($element);
            ?>
            <div class="ui-block-<?php $i = getGridVal($i); ?>"
                <?php if($this->formElementErrors($element)) { echo 'class="error"'; } ?> >

                <?php echo $this->formElement($element); ?>

                <?php if ($formElementErrors): ?>
                    <span class="help-inline">
                        <?php echo $formElementErrors; ?>
                    </span>
                <?php endif; ?>
            </div>
        <?php endforeach; ?>
    <?php echo $formHelper->closeTag(); ?>

    <div id="listResults" style="width:100%;"></div>
</div>
