<?php
$this->headTitle('List');

$order_by  = $this->order_by;
$order     = $this->order;
$paginator = $this->paginator;


$url_order = 'ASC';  // the following lines
if ($order_by == 'title') {
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
} elseif ($order_by == 'artist') {
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
}

$columns = array(
    //'transaction_id' => $this->translate('Id'),
    'item_name'      => $this->translate('Item'),
    'group_name'     => $this->translate('Group'),
    'price'          => $this->translate('Price'),
    //'currency_html'  => $this->translate('Currency'),
    'date'           => $this->translate('Date'),
    //'date_created'   => $this->translate('Created'),
    'id_user'        => $this->translate('User'),
);

$i = 0;


function getGridVal($i)
{
    $iterator = array('a', 'b', 'c', 'd', 'e');
    echo $iterator[$i];
    $i++;
    if ($i >= 5) {
        $i = 0;
    }
    return $i;
}
?>

<div class="ui-grid-d">
    <?php foreach ($columns AS $key => $label) : ?>
        <div class="ui-block-<?php $i = getGridVal($i); ?>">
            <?php

            $icon = sprintf(
                '<i class="icon-chevron-%s"></i>',
                ($url_order == 'ASC' ? 'down' : 'up')
            );

            echo sprintf(
                '<a href="%s">%s</a>',
                $this->url('list', array('order_by' => $key, 'order' => $url_order)),
                $icon . $label
            );

            ?>
        </div>
    <?php endforeach; ?>

    <?php foreach ($this->transactions AS $transaction) : ?>
        <?php foreach ($columns AS $key => $label) : ?>
            <div class="ui-block-<?php $i = getGridVal($i); ?>">
                <?php
                    echo $transaction->getData($key);
                ?>
            </div>
        <?php endforeach; ?>
    <?php endforeach; ?>
</div>

<?php

echo $this->paginationControl(
    $paginator, 'Sliding', 'paginator-slide', array('order_by' => $order_by, 'order' => $order)
);

?>
