<?php
$this->headTitle('New');

$form = $this->form;

$form->setAttribute('action', $this->url('transaction'))
     ->prepare();

echo $this->form()->openTag($form);

/** @var \Zend\Form\Element $element */
foreach ($form as $element) {
    ?>
    <div data-role="fieldcontain">
        <?php
        echo $this->formElement($element);
        ?>
        <ul id="suggestions-<?php echo $element->getName(); ?>"
            data-role="listview"
            data-inset="true"
            class="ui-listview ui-listview-inset ui-corner-all ui-shadow">
        </ul>
    </div>
    <?php
}

echo $this->form()->closeTag();
