<?php
$this->headTitle('New');

$form = $this->form;

$form->setAttribute('action', $this->url('transaction'))
     ->prepare();

echo $this->form()->openTag($form);


foreach ($form as $element) {

    $formElementErrors = $this->formElementErrors($element);

    ?>
    <div  data-role="fieldcontain" <?php if($this->formElementErrors($element)) { echo 'class="error"'; } ?> >

        <?php
        echo $this->formElement($element);

        if ($formElementErrors) {
            ?>
            <span class="help-inline">
                <?php echo $formElementErrors; ?>
            </span>
            <?php
        }
        ?>
    </div>
    <?php
}


foreach ($this->datalist as $name => $values) :
    ?>
    <datalist id="<?php echo $name; ?>s">
        <?php foreach ($values as $value): ?>
            <option value="<?php echo $value; ?>">
        <?php endforeach; ?>
    </datalist>
    <?php
endforeach;


echo $this->form()->closeTag();
//http://raymondcamden.com/index.cfm/2012/3/27/Example-of-Autocomplete-in-jQuery-Mobile