<?php
$this->headTitle('New');

$form = $this->form;

$form->setAttribute('action', $this->url('transaction'))
     ->prepare();

echo $this->form()->openTag($form);

/** @var \Zend\Form\Element $element */
foreach ($form as $element) {
    ?>
    <div data-role="fieldcontain">
        <?php
        echo $this->formElement($element);
        ?>
        <ul id="suggestions-<?php echo $element->getName(); ?>"
            data-role="listview"
            data-inset="true"
            class="ui-listview ui-listview-inset ui-corner-all ui-shadow">
        </ul>
    </div>
    <?php
}

echo $this->form()->closeTag();

?>


<script>
    autocompleteInput(
        $("#item"),
        $('#suggestions-item'),
        <?php echo json_encode($this->datalist['item']); ?>,
        $('#group')
    );

    autocompleteInput(
        $("#group"),
        $('#suggestions-group'),
        <?php echo json_encode($this->datalist['group']); ?>,
        $('#price')
    );

    function autocompleteInput(element, target, data, nextElement)
    {
        var elementId = element.attr('id');
        var targetId  = target.attr('id');
        var nextElementId = nextElement.attr('id');
        element.autocomplete({
            target: target,
            source: data,
            link: '$(\'#' + elementId + '\').val(\'%s\');'
                + '$(\'#' + elementId + '\').trigger(\'input\');'
                + '$(\'#' + targetId + '\')[0].innerHTML=\'\';'
                + '$(\'#' + nextElementId + '\').focus();',
            minLength: 1
        });
    }
</script>