<?php

/** @var \Application\Form\Form\Login $form */
$form = $this->form;

$form->setAttribute('action', $this->url('login'));
$form->prepare();


/** @var \Zend\Form\Element|\Zend\Form\Element\Email    $emailElement    */
/** @var \Zend\Form\Element|\Zend\Form\Element\Password $passwordElement */
/** @var \Zend\Form\Element|\Zend\Form\Element\Submit   $submitElement   */
$emailElement    = $form->get('email');
$passwordElement = $form->get('password');
$submitElement   = $form->get('submit');


$emailElementErrors    = $this->formElementErrors($emailElement);
$passwordElementErrors = $this->formElementErrors($passwordElement);
$submitElementErrors   = $this->formElementErrors($submitElement);

?>

<?php echo $this->form()->openTag($form); ?>

    <div  data-role="fieldcontain" <?php if($emailElementErrors) { echo 'class="error"'; } ?> >
        <?php echo $this->formElement($emailElement); ?>
        <?php if ($emailElementErrors) : ?>
            <span class="help-inline">
                <?php echo $emailElementErrors; ?>
            </span>
        <?php endif; ?>
    </div>

    <div  data-role="fieldcontain" <?php if($passwordElementErrors) { echo 'class="error"'; } ?> >
        <div class="ui-grid-a ui-responsive">
            <div class="ui-block-a">
                <?php echo $this->formElement($passwordElement); ?>
                <?php if ($passwordElementErrors) : ?>
                    <span class="help-inline">
                        <?php echo $passwordElementErrors; ?>
                    </span>
                <?php endif; ?>
            </div>
            <div class="ui-block-b">
                <?php echo $this->formElement($submitElement); ?>
                <?php if ($submitElementErrors) : ?>
                    <span class="help-inline">
                        <?php echo $submitElementErrors; ?>
                    </span>
                <?php endif; ?>
            </div>
        </div>
    </div>

<?php echo $this->form()->closeTag();
