<?php

/** @var \Application\Form\Form\Login $form */
$form = $this->form;

$form->setAttribute('action', $this->url('login'));
$form->prepare();

echo $this->form()->openTag($form);

/** @var \Zend\Form\Element|\Zend\Form\Element\Email $element */
foreach ($form as $element) {

    $formElementErrors = $this->formElementErrors($element);

    ?>
    <div  data-role="fieldcontain" <?php if($this->formElementErrors($element)) { echo 'class="error"'; } ?> >
        <label for="<?php echo $element->getAttribute('name'); ?>"><?php echo $element->getLabel() ?></label>

        <?php
        echo $this->formElement($element);

        if ($formElementErrors) {
            ?>
            <span class="help-inline">
                <?php echo $formElementErrors; ?>
            </span>
            <?php
        }
        ?>
    </div>
    <?php
}

echo $this->form()->closeTag();
