<?php
if (!$this->pageCount){
    return;
}

$params = array(
    'order_by' => $this->vars('order_by'),
    'order'    => $this->vars('order')
);

$show = array(
    'first'    => false,
    'previous' => false,
    'next'     => false,
    'last'     => false,
);

$firstUrl = $this->url('list', array_merge(
    $params, array('page' => $this->first)
));

$previousUrl = $this->url('list', array_merge(
    $params, array('page' => $this->previous)
));

$nextUrl = $this->url('list', array_merge(
    $params, array('page' => $this->next)
));

$lastUrl = $this->url('list', array_merge(
    $params, array('page' => $this->last)
));

$previousDisabled = !isset($this->previous);
$nextDisabled     = !isset($this->next);

$data = array(
    'data-role' => 'button',
    'data-mini' => 'true'
);

$iterator = array('a', 'b', 'c', 'd', 'e');
$maxI = count($iterator) - 1;
$i = 0;
?>


<div style="margin-left: auto; margin-right: auto; width:100%;" >
    <div class="grid-container ui-grid-d ui-responsive" >

        <?php if ($show['first']) : ?>
            <!-- First page link -->
            <div class="ui-block-<?php echo $iterator[$i]; $i = $i >= $maxI ? 0 : ++$i; ?>" >
                <?php
                $rel = '';

                echo sprintf(
                    '<a href="%s" data-role="%s" data-mini="%s" data-theme="%s" %s %s>%s</a>',
                    $firstUrl, $data['data-role'], $data['data-mini'], 'a',
                    ($previousDisabled ? 'class="ui-disabled"' : ''),
                    $rel, '&laquo;'
                );

                ?>
            </div>
        <?php endif; ?>

        <?php if ($show['previous']) : ?>
            <!-- Previous page link -->
            <div class="ui-block-<?php echo $iterator[$i]; $i = $i >= $maxI ? 0 : ++$i; ?>" >
                <?php
                if ($this->current > 1) {
                    $rel = 'rel="prev"';
                } else {
                    $rel = '';
                }

                echo sprintf(
                    '<a href="%s" data-role="%s" data-mini="%s" data-theme="%s" %s %s>%s</a>',
                    $previousUrl, $data['data-role'], $data['data-mini'], 'a',
                    ($previousDisabled ? 'class="ui-disabled"' : ''),
                    $rel, '&lsaquo;'
                );

                ?>
            </div>
        <?php endif; ?>

        <!-- Numbered page links -->
        <?php foreach ($this->pagesInRange as $page): ?>

            <?php
            $url = $this->url('list', array_merge(
                $params, array('page' => $page)
            ));

            if ($this->current - 1 == $page) {
                $rel = 'rel="prev"';
            } elseif ($this->current + 1 == $page) {
                $rel = 'rel="next"';
            } else {
                $rel = '';
            }
            ?>

            <div class="ui-block-<?php echo $iterator[$i]; $i = $i >= $maxI ? 0 : ++$i; ?>" >
                <?php

                echo sprintf(
                    '<a href="%s" data-role="%s" data-mini="%s" data-theme="%s" %s %s>%s</a>',
                    $url, $data['data-role'], $data['data-mini'],
                    ($page == $this->current ? 'b' : 'a'), '', $rel, $page
                );

                ?>
            </div>
        <?php endforeach; ?>

        <?php if ($show['next']) : ?>
            <!-- Next page link -->
            <div class="ui-block-<?php echo $iterator[$i]; $i = $i >= $maxI ? 0 : ++$i; ?>" >
                <?php

                if ($this->current < $this->pageCount) {
                    $rel = 'rel="next"';
                } else {
                    $rel = '';
                }

                echo sprintf(
                    '<a href="%s" data-role="%s" data-mini="%s" data-theme="%s" %s %s>%s</a>',
                    $nextUrl, $data['data-role'], $data['data-mini'], 'a',
                    ($nextDisabled ? 'class="ui-disabled"' : ''), $rel, '&rsaquo;'
                );

                ?>
            </div>
        <?php endif; ?>

        <?php if ($show['last']) : ?>
            <!-- Last page link -->
            <div class="ui-block-<?php echo $iterator[$i]; $i = $i >= $maxI ? 0 : ++$i; ?>" >
                <?php

                echo sprintf(
                    '<a href="%s" data-role="%s" data-mini="%s" data-theme="%s" %s>%s</a>',
                    $lastUrl, $data['data-role'], $data['data-mini'], 'a',
                    ($nextDisabled ? 'class="ui-disabled"' : ''), '&raquo;'
                );

                ?>
            </div>
        <?php endif; ?>
    </div>
</div>
