<?php if ($this->pageCount): ?>

    <?php

        $firstUrl = $this->url('list', array(
            'page'     => $this->first,
            'order_by' => $order_by,
            'order'    => $order
        ));

        $previousUrl = $this->url('list', array(
            'page'     => $this->previous,
            'order_by' => $order_by,
            'order'    => $order
        ));

        $nextUrl = $this->url('list', array(
            'page'     => $this->next,
            'order_by' => $order_by,
            'order'    => $order
        ));

        $lastUrl = $this->url('list', array(
            'page'     => $this->last,
            'order_by' => $order_by,
            'order'    => $order
        ));

        $previousDisabled = !isset($this->previous);
        $nextDisabled     = !isset($this->next);

        $data = 'data-role="button" data-mini="true"';
    ?>

<!--<div data-theme="b" data-role="footer" data-position="fixed">-->
<div>

    <div data-role="navbar" class="ui-navbar ui-mini" role="navigation">
        <ul class="navigation ui-grid" >

            <!-- First page link -->
            <li>
                <a
                    href="<?php echo $firstUrl; ?>"
                    <?php echo $data; ?>
                    data-theme="a"
                    <?php echo $previousDisabled ? 'class="ui-disabled"' : ''; ?>
                >
                    &laquo;
                </a>
            </li>

            <!-- Previous page link -->
            <li>
                <a
                    href="<?php echo $previousUrl; ?>"
                    <?php echo $data; ?>
                    data-theme="a"
                    <?php echo $previousDisabled ? 'class="ui-disabled"' : ''; ?>
                >
                    &lsaquo;
                </a>
            </li>

            <!-- Numbered page links -->
            <?php foreach ($this->pagesInRange as $page): ?>

                <?php
                $url = $this->url('list', array(
                    'page'     => $page,
                    'order_by' => $order_by,
                    'order'    => $order
                ));

                $active = $this->current;
                ?>

                <li>
                    <a
                        href="<?php echo $url; ?>"
                        <?php echo $data; ?>
                        <?php echo $page == $active ? 'data-theme="b"' : 'data-theme="a"'; ?>
                    >
                        <?php echo $page; ?>
                    </a>
                </li>
            <?php endforeach; ?>

            <!-- Next page link -->
            <li>
                <a
                    href="<?php echo $nextUrl; ?>"
                    <?php echo $data; ?>
                    data-theme="a"
                    <?php echo $nextDisabled ? 'class="ui-disabled"' : ''; ?>
                >
                    &rsaquo;
                </a>
            </li>

            <!-- Last page link -->
            <li>
                <a
                    href="<?php echo $lastUrl; ?>"
                    <?php echo $data; ?>
                    data-theme="a"
                    <?php echo $nextDisabled ? 'class="ui-disabled"' : ''; ?>
                >
                    &raquo;
                </a>
            </li>
        </ul>
    </div>
</div>
<?php endif; ?>