<div class="ui-grid-a">
    <div class="ui-block-a">
        <div id="dino"></div>
    </div>
    <div class="ui-block-b">
        <ul data-role="listview" id="right-block">
            <li>
                <?php
                echo $this->partial(
                    'application/login/index.phtml',
                    array('form' => $this->loginForm)
                );
                ?>
            </li>
            <li id="register-block">
                <h2><strong>New to Twitter?</strong> Sign up</h2>
                <?php
                echo $this->partial(
                    'application/register/index.phtml',
                    array('form' => $this->registerForm)
                );
                ?>
            </li>
        </ul>
    </div>
</div>