<?php
$this->headTitle('User');
?>

<div data-role="tabs" id="tabs">
    <div data-role="navbar">
        <ul>
            <li><a href="#logout" data-ajax="false"><?php echo $this->translate('Logout'); ?></a></li>
            <li><a href="#data" data-ajax="false"><?php echo $this->translate('Data'); ?></a></li>
            <li><a href="#connection" data-ajax="false"><?php echo $this->translate('Connections'); ?></a></li>
            <li><a href="#config" data-ajax="false"><?php echo $this->translate('Config'); ?></a></li>
        </ul>
    </div>

    <div id="logout">
        <div style="width:18em;margin-top:2em;margin-left:auto;margin-right:auto;">
            <a href="<?php echo $this->url('logout'); ?>"
               data-ajax="false"
               data-role="button"
               data-icon="power"
               data-mini="true"
               data-theme="a" >
                <?php echo $this->translate('Logout'); ?>
            </a>
        </div>
    </div>

    <div id="connection">
        <table data-role="table" class="ui-responsive table-stroke">
            <?php
            $userId = $this->userId;
            $columns = array(
                //'connection_id' => $this->translate('Id'),
                'email'        => $this->translate('Email'),
                'date_created' => $this->translate('Date'),
                'state'        => $this->translate('State'),
            );

            echo '<thead>';
                echo '<tr>';
                    foreach ($columns as $label) {
                        echo '<th>' . $label . '</th>';
                    }
                echo '</tr>';
            echo '</thead>';
            echo '<tbody>';

                /** @var \Zend\Db\ResultSet\HydratingResultSet $connections */
                /** @var \Application\Db\Connection $connection */
                $connections = $this->connections;
                foreach ($connections as $connection) {
                    echo '<tr>';
                        foreach ($columns as $key => $label) {
                            echo '<td>';
                            if ($key == 'state' && $userId == $connection->getIdUser()) {
                                $stateRejected = \Application\Db\Connection::STATE_REJECTED;
                                $action = $connection->getState() == $stateRejected ? 'accept' : 'reject';
                                $icon   = $connection->getState() == $stateRejected ? 'check' : 'delete';
                                $label  = $connection->getState() == $stateRejected ? 'Accept' : 'Revoke';

                                $url = $this->url('connection', array('action' => $action));
                                $url .= '?id=' . $connection->getConnectionId();
                                ?>
                                <a href="<?php echo $url; ?>"
                                   data-ajax="false"
                                   data-role="button"
                                   data-icon="<?php echo $icon; ?>"
                                   data-mini="true"
                                   data-theme="a" >
                                    <?php echo $this->translate($label); ?>
                                </a>
                                <?php
                            } else {
                                echo $connection->getData($key);
                            }
                            echo '</td>';
                        }
                    echo '</tr>';
                }
            echo '</tbody>';
            ?>
        </table>

        <div style="width:18em;margin-top:2em;margin-left:auto;margin-right:auto;">
            <a href="<?php echo $this->url('connection'); ?>"
               data-ajax="false"
               data-role="button"
               data-icon="plus"
               data-mini="true"
               data-theme="a" >
                <?php echo $this->translate('Connection'); ?>
            </a>
        </div>
    </div>

    <div id="config" style="display:none;">
        <?php
        $form = $this->form;

        $form->setAttribute('action', $this->url('user'))
             ->prepare();

        echo $this->form()->openTag($form);

        foreach ($form as $element) {

            $formElementErrors = $this->formElementErrors($element);

            ?>
            <div  data-role="fieldcontain" <?php if($this->formElementErrors($element)) { echo 'class="error"'; } ?> >
                <label for="<?php echo $element->getAttribute('name'); ?>"><?php echo $element->getLabel() ?></label>

                <?php
                echo $this->formElement($element);

                if ($formElementErrors) {
                    ?>
                    <span class="help-inline">
                        <?php echo $formElementErrors; ?>
                    </span>
                    <?php
                }
                ?>
            </div>
            <?php
        }

        echo $this->form()->closeTag();
        ?>
    </div>
    <div id="data">
        <?php
        echo $this->partial(
            'application/data/index.phtml',
            array()
        );
        ?>
    </div>
</div>