<?php
/**
 * @var $form Application\Form\Form\Month
 */
$form = $this->form;

$form->setAttribute('action', $this->url('pie', array(
    'action' => 'filter',
)));
$form->prepare();

echo $this->form()->openTag($form);


foreach ($form as $element) {

$formElementErrors = $this->formElementErrors($element);

?>
<div  data-role="fieldcontain" <?php if($this->formElementErrors($element)) { echo 'class="error"'; } ?> >
    <label for="<?php echo $element->getAttribute('name'); ?>"><?php echo $element->getLabel() ?></label>

    <?php
    echo $this->formElement($element);

    if ($formElementErrors) {
        ?>
        <span class="help-inline">
                <?php echo $formElementErrors; ?>
            </span>
    <?php
    }
    ?>
</div>
<?php
}

echo $this->form()->closeTag();

?>

<div id="container" style="width:100%;height:80%;" ></div>


<script type="text/javascript">

    var colors     = Highcharts.getOptions().colors,
        categories = <?php echo json_encode($this->groupNames); ?>,
        data       = <?php echo $this->chartData->renderOptions(); ?>;

    var primaryData   = [];
    var secondaryData = [];

    for (var i = 0; i < data.length; i++) {

        primaryData.push({
            name  : categories[i],
            y     : data[i].y,
            color : data[i].color
        });

        for (var j = 0; j < data[i].drilldown.data.length; j++) {
            var brightness = 0.2 - (j / data[i].drilldown.data.length) / 5;
            secondaryData.push({
                name  : data[i].drilldown.categories[j],
                y     : data[i].drilldown.data[j],
                color : Highcharts.Color(data[i].color).brighten(brightness).get()
            });
        }
    }

</script>
