<?php
/**
 * @var $form Application\Form\Form\Month
 * @var $this \Zend\View\Renderer\PhpRenderer
 */
$form = $this->form;

$form->setAttribute('action', $this->url('pie', array(
    'action' => 'filter',
)));
$form->prepare();

echo $this->form()->openTag($form);


foreach ($form as $element) {

$formElementErrors = $this->formElementErrors($element);

?>
<div  data-role="fieldcontain" <?php if($this->formElementErrors($element)) { echo 'class="error"'; } ?> >
    <label for="<?php echo $element->getAttribute('name'); ?>"><?php echo $element->getLabel() ?></label>

    <?php
    echo $this->formElement($element);

    if ($formElementErrors) {
        ?>
        <span class="help-inline">
                <?php echo $formElementErrors; ?>
            </span>
    <?php
    }
    ?>
</div>
<?php
}

echo $this->form()->closeTag();

?>

<div id="container" style="width:100%;height:100%;" ></div>


<script type="text/javascript">
    var colors   = Highcharts.getOptions().colors,
        groups   = <?php echo json_encode($this->groupNames); ?>,
        groupIds = <?php echo json_encode($this->groupIds); ?>,
        data     = <?php echo $this->chartData->renderOptions(); ?>;

    console.log(data);

    var primaryData   = [];
    var secondaryData = [];

    for (var i = 0; i < data.length; i++) {

        primaryData.push({
            name  : groups[i],
            id    : groupIds[i],
            type  : "group",
            y     : data[i].y,
            color : data[i].color
        });

        for (var j = 0; j < data[i].drilldown.data.length; j++) {
            var brightness = 0.2 - (j / data[i].drilldown.data.length) / 5;
            secondaryData.push({
                name  : data[i].drilldown.items[j],
                type  : data[i].drilldown.types[j],
                y     : data[i].drilldown.data[j],
                color : Highcharts.Color(data[i].color).brighten(brightness).get(),
                id_group : data[i].drilldown.id_groups[j],
                id_item  : data[i].drilldown.id_items[j]
            });
        }
    }
</script>
